name: Node Image Build and Push to Github Container Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      env:
        ghcr_user: ${{ secrets.ghcr_user }}   
        CR_PAT: ${{ secrets.CR_PAT }}  
          
      run: |
        docker login ghcr.io -u $ghcr_user -p $CR_PAT 

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: docker build image
      env:
        ghcr_user: ${{ secrets.ghcr_user }} 
      run: |
        docker build -t ghcr.io/$ghcr_user/nodejs:latest . 
    - name: docker push image to ghcr
      env:
        ghcr_user: ${{ secrets.ghcr_user }} 
      run: |
        docker push ghcr.io/$ghcr_user/nodejs:latest