name: Node Image Build and Push to Github Container Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      env:
        ghcr_user: ${{ secrets.ghcr_user }}   
        CR_PAT: ${{ secrets.CR_PAT }}  
          
      run: |
        docker login ghcr.io -u $ghcr_user -p $CR_PAT 

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: docker build image
      env:
        ghcr_user: ${{ secrets.ghcr_user }} 
      run: |
        docker build -t ghcr.io/$ghcr_user/nodejs:latest . 
    - name: docker push image to ghcr
      env:
        ghcr_user: ${{ secrets.ghcr_user }} 
      run: |
        docker push ghcr.io/$ghcr_user/nodejs:latest
    - name: triggering jenkins
      env:
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      run: |
        curl -I -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PASSWORD }} http://jenkins.89c360e5-5b6d-49b3-b43d-33c5a9f94213.k8s.civo.com/job/civo_deployment/build?token=${secrets.JENKINS_TOKEN}